installdir = $(datadir)/enigma2/MaterialDark/buttons

dist_install_DATA = blue.svg green.svg key_0.svg key_help.svg key_info.svg key_menu.svg \
                    key_next.svg key_ok.svg key_prev.svg key_right.svg key_text.svg \
                    left.svg rec.svg red.svg right.svg stream.svg yellow.svg
