installdir = $(datadir)/enigma2/MaterialDark/icons

dist_install_DATA = agreen.svg aoff.svg ared.svg ayellow.svg \
                    chevronleft.svg chevronlefttrans.svg chevronright.svg chevronrighttrans.svg \
                    icon_view.svg lock_off.svg lock_on.svg menu_off.svg menu_on.svg \
                    mp_backward.svg mp_forward.svg mp_pause.svg mp_play.svg mp_slow.svg mp_stop.svg \
                    scan-c.svg scan-s.svg scan-t.svg update_stable.svg vkey_icon.svg
