installdir = $(datadir)/enigma2/MaterialDark/infobar

dist_install_DATA = ico_crypt_on.svg ico_dolby_on.svg ico_format_16_9.svg ico_format_4_3.svg \
                    ico_format_4k.svg ico_format_hd.svg ico_hbbtv_on.svg ico_pdc.svg \
                    ico_sub_on.svg ico_txt_on.svg mute.svg vol_box.svg volumeslider.svg
